repos:
  -
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      # Commit
      - id: check-added-large-files   # prevents giant files from being committed
      - id: detect-aws-credentials    # detects aws credentials
      - id: detect-private-key        # detects the presence of private keys
      # Syntax
      - id: check-ast                 # checks whether the files parse as valid python
      - id: check-json                # checks json files for parseable syntax
      - id: check-yaml                # checks yaml files for parseable syntax
      # Style
      - id: trailing-whitespace       # trims trailing whitespace
      - id: requirements-txt-fixer    # sorts entries in requirements.txt

  -
    repo: https://github.com/kynan/nbstripout
    rev: 0.6.1
    hooks:
      # Commit
      - id: nbstripout                # strip output from Jupyter and IPython notebooks