version: '3'


services:
  source_postgres:
    image: postgres:9.2
    ports:
      - '5543:5432'
    environment:
      POSTGRES_DB: source_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    networks:
      - elt_network
    volumes:
      - ./source_db_init/init.sql:/docker-entrypoint-initdb.d/init.sql

  destination_postgres:
    image: postgres:9.2
    ports:
      - '5544:5432'
    environment:
      POSTGRES_DB: destination_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    networks:
      - elt_network

  elt_script:
    build:
      context: ./elt
      dockerfile: Dockerfile
    command: [ "python", "elt_script.py" ]
    networks:
      - elt_network
    depends_on:
      - source_postgres
      - destination_postgres


networks:
  elt_network:
    driver: bridge